spring:
  application:
    name: devlog
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/devlog?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:devlog}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

jwt:
  secret: ${JWT_SECRET:}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:1h}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:14d}

server:
  port: 8080
  error:
    include-message: never
    include-stacktrace: never
    include-exception: false
    include-binding-errors: never
